### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by EightiesPower** [sony/genwarp#1] opened 2024-08-29 19:47 UTC
When I run the app.py after installing the dependencies and models, I get the following error:

Traceback (most recent call last):
  File "G:\stable diffusion stuff\genwarp\app.py", line 5, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

I'd appreciate it if someone could explain what I'm doing wrong. Thank you.

**Comment by j0seo** [comment] 2024-08-30 02:16
Hi @EightiesPower , have you installed the libraries in 'requirements_dev.txt'? Also, it looks like you are using Windows. We have not tested our model on Windows yet. please let us know if you have any further issues!

**Comment by kaz-sony** [comment] 2024-09-01 05:02
Hi @EightiesPower , The error message says that your python environment couldn't find 'gradio' package. Could you check that gradio is installed in your environment as @j0seo mentioned? And also, please read through [how to section](https://github.com/sony/genwarp?tab=readme-ov-file#how-to-use) in the readme again and tell us with more details for us to investigate on it when the problem persists. If no further assistance is needed, I'd like to close this issue. Thank you.

**Comment by EightiesPower** [comment] 2024-09-01 21:45
Strange, I was sure I had run the requirements_dev.txt, but I tried running it again and it did install gradio among other things. Now, however, I get  an error: "ModuleNotFoundError: No module named 'splatting'". And when I run the "pip install git+https://github.com/pesser/splatting" command  , I get the following error: 
error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\tazbi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\tazbi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tazbi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tazbi\AppData\Local\Temp\pip-build-env-7cdxqmzy\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tazbi\AppData\Local\Temp\pip-build-env-7cdxqmzy\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\tazbi\AppData\Local\Temp\pip-build-env-7cdxqmzy\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\tazbi\AppData\Local\Temp\pip-build-env-7cdxqmzy\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

But when I run the "python -c "import torch; print(torch.__version__)"" command, it shows that I have the
2.0.1+cpu version of Torch installed.

**Comment by kaz-sony** [comment] 2024-09-01 23:37
Hi @EightiesPower , Thank you for giving us details. It seems you're on a Windows machine without a GPU judging from the stack trace. We'are sorry that we didn't test it on and will not support such kind of machines.
I'm closing this issue because the problem is rather on the user's specific environmental setup than the codes on the repository. If you find any bugs, please feel free to open a new issue. Thank you.

**Closed as completed by kaz-sony** 2024-09-01 23:37 UTC

**Comment by kaz-sony** [comment] 2024-09-02 00:00
As a side note, you can try Docker to virtually recreate a linux environment as mentioned in the [readme](https://github.com/pesser/splatting) (though a GPU is still required) or you can try it out on our [Spaces](https://huggingface.co/spaces/Sony/genwarp) without bothering you too much if you just want to get your hands on it.

**Comment by EightiesPower** [comment] 2024-09-02 10:59
> Hi @EightiesPower , Thank you for giving us details. It seems you're on a Windows machine without a GPU judging from the stack trace. We'are sorry that we didn't test it on and will not support such kind of machines. I'm closing this issue because the problem is rather on the user's specific environmental setup than the codes on the repository. If you find any bugs, please feel free to open a new issue. Thank you.

Uuh, I have an RTX 3090 with the latest studio driver.

**Comment by kaz-sony** [comment] 2024-09-02 11:50
That seems to be enough to run the model. Did you install CUDA toolkit? It is required to install CUDA version of pytorch. That is possibly one of the reasons. Other than that, I recommend to use some kind of virtual environment in order to setup python such as conda and venv. On top of that,  a virtual machine is generally recommended in order to avoid any conflict of versions between other projects and ours. You may want do check out our Dockerfile example. Thank you for your interest!

**Comment by EightiesPower** [comment] 2024-09-02 19:22
It says my CUDA version is Build cuda_12.1.r12.1/compiler.32415258_0
I have set up and activated a venv before running requirements. 
I may look into Dockerfile though I'm not familiar with this tool. Thanks for your help.
